### ISSUE TITLE
'cargo ios/app' might be much better than 'cargo xcodebuild'

### ISSUE THREAD

**Issue by SakulFlee** [Gordon-F/cargo-xcodebuild#1]
Hello there!

I just wanted to share a thought with you:  
I've been searching for a tool **just like this one** for quite some time now. 
Essentially an `cargo apk` but for ios.
But I never found this project due to its 'weird' naming.

I always searched for "cargo ios" and similar tools and only by pure chance did I found a blog article talking about this tool while trying to figure out how to use `xcodegen`  with Rust.

My suggestion would be to rename this tool to `cargo ios` (following the same schema as `cargo apk`) _or maybe `cargo app`_. This would make it much more clearer what this project is about (building iOS apps with Rust!), without needing to know much about `xcodegen`.
Furthermore, it would greatly improve the search index.

If wanted/required I can assist and contribute as well :)
Have a nice day!

**Comment by Gordon-F** [comment]
Hi, thank you! The name `cargo xcodebuild` was chosen because `xcodebuild` is the main tool for building iOS/MacOS apps. It's a part of Xcode's bundled command-line tools package.
